### ISSUE TITLE
Please publish the new updates to npm package

### ISSUE THREAD

**Issue by summerkiflain** [MikePodgorniy/react-native-conical-gradient-progress#13]
I have been waiting for new changes to be published to npm since 2 weeks, please publish, Thanks.

**Comment by ankitjaiswal1994** [comment]
@summerkiflain It has been years. So kindly directly use it.

**Comment by summerkiflain** [comment]
@ankitjaiswal1994 how can I use it directly?

**Comment by ankitjaiswal1994** [comment]
Fork the master branch of this repo onto yours.
 In package.json do the below changes:

Instead of
    "react-native-conical-gradient-progress": "1.0.0"
to 
    "react-native-conical-gradient-progress": "Your github url"

**Comment by summerkiflain** [comment]
@ankitjaiswal1994 Thanks for the guidelines, really appreciate it.
