### ISSUE TITLE
Some information 

### ISSUE THREAD

**Issue by Angelk90** [MikePodgorniy/react-native-conical-gradient-progress#2]
Hi @MikePodgorniy, Some doubts:
1) I do not understand why in the package did you put svg in the package.json?
2) I tried to convert your module to try it on https://snack.expo.io/
I am given the following error:
TypeError: undefined is not an object (evaluating 'o.map')
Line 27 of CircularProgress:
Here is the link where you can try it: https://snack.expo.io/HkDheSJmE
3) You could improve the documentation I do not understand what serves prefill and segments.
4) It would be interesting to be able to animate itself for example, click on Play and at intervals defined for example every 3.33 is removed from 100% and when it reaches a value defined for example 0% then you start a function defined as props.

**Comment by MikePodgorniy** [comment]
1. I don't have a lot of experience in the npm packages, it's my first package. You need to install react-native-svg manually or use expo. Usually, you can use some different packages with react-native-svg in peerDependency like react-native-svg-charts, react-native-conical-gradient-progress. And those packages will be located on one level:
```
node_modules/
  react-native-svg
  react-native-svg-charts
  react-native-conical-gradient-progress
```
2. You should replace `<LinearGradient>` to `<Svg.LinearGradient>`
3. Ok. Prefill is a start position in progress. Segments are to create a conical gradient before rendering we need to calculate n-segments like LinearGradient and drawing paths with those gradients. The more segments you use, the smoother gradient you get.
4. Ok, I want to replace logic to use mask and static gradient circle, maybe it will incriese perfomance and give an opportunity to use smoother gradient.
