### ISSUE TITLE
Error: Unable to parse color from string: rgb (NaN,NaN,Nan)

### ISSUE THREAD

**Issue by vjandrei** [MikePodgorniy/react-native-conical-gradient-progress#3]
I just try the package to my project and I got this rgb error.

![screenshot_1548607067](https://user-images.githubusercontent.com/196690/51803892-b7f5f600-2262-11e9-806a-c3226ee94099.png)

**Comment by MikePodgorniy** [comment]
Can you show example?

вс, 27 янв. 2019 г. в 18:38, Andreas <notifications@github.com>:

**Comment by vjandrei** [comment]
Right I need to segments={16} here 👍
