### ISSUE TITLE
arcSweepAngle

### ISSUE THREAD

**Issue by vjandrei** [MikePodgorniy/react-native-conical-gradient-progress#4]
Is there possible to have arcSweepAngle ?

**Comment by vjandrei** [comment]
I would liked to get something like this.
![galaxy s8](https://user-images.githubusercontent.com/196690/51805864-61e17c80-227b-11e9-8463-29452f58f7e9.jpg)

**Comment by MikePodgorniy** [comment]
_The Simple Way_ 

**Background**
Change  endAngle(2 * Math.PI);
https://github.com/MikePodgorniy/react-native-conical-gradient-progress/blob/5c46b922b5e932d993a4b34703779a550f95edbd/CircularProgress.js#L101-L105

**EndCircle**
Change Circle Fill, Add Stroke
https://github.com/MikePodgorniy/react-native-conical-gradient-progress/blob/5c46b922b5e932d993a4b34703779a550f95edbd/CircularProgress.js#L149-L164

Use BaseComponent Fill from 0..75-80 :)
